package com.yedam;

import java.util.Scanner;

import org.junit.jupiter.api.Test;

class Score{
	
	public void input() throws Exception {
		Scanner scan = new Scanner(System.in);
		
		int n1 = scan.nextInt();
		int n2 = scan.nextInt();
		int n3 = total(n1, n2);
		
		System.out.println("result" + n3);
	}
	
	public int total(int n1, int n2) throws Exception {
		//에러생성
		if(n1 < 0 || n2 < 0) {
			throw new Exception("음수 입력");  
		}
		int result = n1 + n2;
		return result;
	}
	
}

public class ExceptionTest {
	@Test
	public void test(){
		//객세 생성
		Score sco = new Score();
		try {
			sco.input(); 			//input  메서드 호출(실행)
		} catch (Exception e) {   //catch에서 에러를 throws된 에러를 잡음. 
			System.out.println(e.getMessage());
		}
		System.out.println("the end");

	}
}
